### ISSUE TITLE
Merge milux/ctldap

### ISSUE THREAD

**Issue by sscholl** [churchtools/ctldap#1]
Hallo,
Das Projekt sollte dringend mit milux/ctldap gemerged werden!
https://github.com/milux/ctldap/

Grüße
sscholl

**Comment by sscholl** [comment]
Schade, dass ihr inaktiv seid...

**Comment by djschilling** [comment]
@sscholl warum sollten wir den LDAP-Wrapper von @milux mergen?

Wir empfehlen sowieso immer schon den LDAP-Wrapper von @milux zu benutzen.

Ich kann das mal noch in unsere README schreiben.

**Comment by djschilling** [comment]
Ich habe die README aktuallisiert um das klar zu machen.

**Comment by sscholl** [comment]
Vielen Dank!
